pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:

  - name: node
    image: node:18
    command: ["cat"]
    tty: true

  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli
    command: ["cat"]
    tty: true

  - name: dind
    image: docker:dind
    args:
      - "--storage-driver=overlay2"
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""

'''
        }
    }

    environment {
        SONARQUBE = "IMCC-Sonar"     // MUST match Jenkins configured name
        DOCKER_IMAGE = "dsa-client"
    }

    stages {

        stage("CHECK") {
            steps {
                echo "DSA Visualization Pipeline Started"
            }
        }

        /* FRONTEND INSTALL + BUILD */
        stage('Install + Build Frontend') {
            steps {
                dir('client') {
                    container('node') {
                        sh '''
                            echo "Installing npm dependencies..."
                            npm install

                            echo "Building Vite project..."
                            npm run build
                        '''
                    }
                }
            }
        }

        /* SONARQUBE */
        stage('SonarQube Analysis') {
            steps {
                container('sonar-scanner') {
                    withSonarQubeEnv("${SONARQUBE}") {
                        sh '''
                            sonar-scanner \
                              -Dsonar.projectKey=dsa-client \
                              -Dsonar.sources=client/src \
                              -Dsonar.host.url=http://sonarqube.imcc.com \
                              -Dsonar.login=$SONARQUBE_AUTH_TOKEN
                        '''
                    }
                }
            }
        }

        stage('Wait for Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        /* DOCKER BUILD */
        stage("Build Docker Image") {
            steps {
                container("dind") {
                    sh """
                        docker build -t ${DOCKER_IMAGE}:latest client/
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}