pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:

  - name: node
    image: node:18
    command: ["cat"]
    tty: true

  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli
    command: ["cat"]
    tty: true

  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["cat"]
    tty: true
    securityContext:
      runAsUser: 0
      readOnlyRootFilesystem: false
    env:
      - name: KUBECONFIG
        value: /kube/config
    volumeMounts:
      - name: kubeconfig-secret
        mountPath: /kube/config
        subPath: kubeconfig

  - name: dind
    image: docker:dind
    securityContext:
      privileged: true
    env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
    volumeMounts:
      - name: docker-config
        mountPath: /etc/docker/daemon.json
        subPath: daemon.json

  volumes:
    - name: docker-config
      configMap:
        name: docker-daemon-config

    - name: kubeconfig-secret
      secret:
        secretName: kubeconfig-secret
'''
        }
    }

    environment {
        PROJECT_KEY = "2401003-DSAV"
        IMAGE_NAME = "dsa-visualization"
        NAMESPACE = "2401003"
        REGISTRY = "nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085"
        REPO = "2401003-project"
    }

    stages {

        /* ============================
              1. FRONTEND BUILD
        ============================== */
        stage('Build Frontend') {
            steps {
                dir('client') {
                    container('node') {
                        sh '''
                            echo "Installing dependencies..."
                            npm install

                            echo "Building Vite project..."
                            npm run build
                        '''
                    }
                }
            }
        }

        /* ============================
             2. TESTS
        ============================== */
        stage('Run Tests') {
            steps {
                echo "No tests added. Skipping."
            }
        }

        /* ============================
             3. SONARQUBE
        ============================== */
        stage('SonarQube Analysis') {
            steps {
                container('sonar-scanner') {
                    withCredentials([string(credentialsId: 'sonar-token-2401003', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            sonar-scanner \
                                -Dsonar.projectKey=2401003-DSAV \
                                -Dsonar.sources=client/src \
                                -Dsonar.host.url=http://my-sonarqube-sonarqube.sonarqube.svc.cluster.local:9000 \
                                -Dsonar.login=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }

        /* ============================
             4. DOCKER LOGIN
        ============================== */
        stage('Login to Docker Registry') {
            steps {
                container('dind') {
                    sh '''
                        docker --version
                        sleep 10
                        docker login $REGISTRY -u admin -p Changeme@2025
                    '''
                }
            }
        }

        /* ============================
             5. BUILD - TAG - PUSH
        ============================== */
        stage('Build - Tag - Push Image') {
            steps {
                container('dind') {
                    sh '''
                        docker build -t ${IMAGE_NAME}:latest ./client
                        docker tag ${IMAGE_NAME}:latest ${REGISTRY}/${REPO}/${IMAGE_NAME}:latest
                        docker push ${REGISTRY}/${REPO}/${IMAGE_NAME}:latest
                        docker image ls
                    '''
                }
            }
        }

        /* ============================
              6. CREATE NAMESPACE
        ============================== */
        stage('Create Namespace if not exists') {
            steps {
                container('kubectl') {
                    sh '''
                        echo "Checking namespace..."
                        kubectl get namespace ${NAMESPACE} || kubectl create namespace ${NAMESPACE}
                    '''
                }
            }
        }

        /* ============================
              7. DEPLOY TO K8s
        ============================== */
        stage('Deploy to Kubernetes') {
            steps {
                container('kubectl') {
                    script {
                        dir('k8s') {
                            sh '''
                                echo "Applying Kubernetes Deployment..."
                                kubectl apply -n ${NAMESPACE} -f deployment.yaml
                               
                            '''
                        }
                    }
                }
            }
        }
    }

    post {
        always {
           // cleanWs()
           deleteDir()
        }
    }
}